// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotesManager.DAL.Persistence;

#nullable disable

namespace NotesManager.DAL.Migrations
{
    [DbContext(typeof(NotesManagerDbContext))]
    partial class NotesManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotesManager.DAL.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            Content = "This is your first note. Start organizing your thoughts and ideas!",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Welcome to Notes"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            Content = "Remember to update the team on your progress during the standup meeting.",
                            CreatedAt = new DateTime(2024, 1, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Daily Standup"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440003"),
                            Content = "Complete the API implementation and testing by end of this week.",
                            CreatedAt = new DateTime(2024, 1, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Project Deadline",
                            UpdatedAt = new DateTime(2024, 1, 14, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440004"),
                            Content = "Focus on logic, performance, and code style. Be constructive with feedback.",
                            CreatedAt = new DateTime(2024, 1, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Code Review Tips"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440005"),
                            Content = "Discussed Q1 goals, team expansion, and new technology stack adoption.",
                            CreatedAt = new DateTime(2024, 1, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Meeting Notes",
                            UpdatedAt = new DateTime(2024, 1, 13, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
